require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/movements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Movement. As you add validations to Movement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Movement.create! valid_attributes
      get movements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      movement = Movement.create! valid_attributes
      get movement_url(movement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_movement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      movement = Movement.create! valid_attributes
      get edit_movement_url(movement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Movement" do
        expect {
          post movements_url, params: { movement: valid_attributes }
        }.to change(Movement, :count).by(1)
      end

      it "redirects to the created movement" do
        post movements_url, params: { movement: valid_attributes }
        expect(response).to redirect_to(movement_url(Movement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Movement" do
        expect {
          post movements_url, params: { movement: invalid_attributes }
        }.to change(Movement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post movements_url, params: { movement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested movement" do
        movement = Movement.create! valid_attributes
        patch movement_url(movement), params: { movement: new_attributes }
        movement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the movement" do
        movement = Movement.create! valid_attributes
        patch movement_url(movement), params: { movement: new_attributes }
        movement.reload
        expect(response).to redirect_to(movement_url(movement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        movement = Movement.create! valid_attributes
        patch movement_url(movement), params: { movement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested movement" do
      movement = Movement.create! valid_attributes
      expect {
        delete movement_url(movement)
      }.to change(Movement, :count).by(-1)
    end

    it "redirects to the movements list" do
      movement = Movement.create! valid_attributes
      delete movement_url(movement)
      expect(response).to redirect_to(movements_url)
    end
  end
end
